import { GameEvent } from '@/types/game';
import { C } from '@/theme/theme';

/** The bread-and-mud staples of village life. Available to low ranks. */
export const PEASANT_EVENTS: GameEvent[] = [
  {
    id: 'peasant_quack_doctor',
    category: 'peasant',
    title: 'THE QUACK DOCTOR',
    text: "A 'physician' offers a magic healing crystal for 6 gold. It is visibly a pebble.",
    ageMin: 8,
    ranks: ['Peasant', 'Squire'],
    choices: [
      { label: 'Buy the healing pebble (6g)', costGold: 6, outcome: { text: 'You bought the pebble. It did nothing, but you feel optimistic. That counts for something.', effects: { gold: -6, health: 3, wits: -3 }, tone: 'plain' } },
      { label: 'Politely decline', outcome: { text: 'You declined. The doctor moved on to a more gullible peasant.', effects: { wits: 4 }, tone: 'good' } },
      { label: 'Steal the pebble and run', outcome: { text: "You snatched the pebble and bolted. It's still just a pebble, but it's YOUR pebble now.", effects: { gold: 4, faith: -5, charm: -2, path: { outlaw: 1 } }, tone: 'plain' } },
    ],
  },
  {
    id: 'peasant_rat_granary',
    category: 'peasant',
    title: 'A RAT IN THE GRANARY',
    text: 'A fat rat is eating the village’s winter grain. The elders look at you, the nearest fool.',
    ageMin: 8,
    ranks: ['Peasant', 'Squire'],
    choices: [
      { label: 'Hunt it with a broom', outcome: { text: 'After an epic broom-duel, the rat fled. The village cheered. You bled slightly.', effects: { health: -4, charm: 6, gold: 3, reputation: 2 }, tone: 'good' } },
      { label: 'Befriend it', outcome: { text: 'You named the rat Geoffrey. Geoffrey now eats your grain too. Worth it.', effects: { charm: 4, wits: -2 }, tone: 'plain' } },
      { label: 'Blame Sir Quackbeard', outcome: { text: 'You blamed the goose. The goose knows. The goose will remember.', effects: { faith: -4, kinRel: { id: 'goose', delta: -10 } }, tone: 'bad' } },
    ],
  },
  {
    id: 'peasant_lords_tourney',
    category: 'peasant',
    title: 'THE LORD’S TOURNEY',
    text: 'A jousting tourney is held! Peasants may enter for 5 gold and probable death.',
    ageMin: 14,
    ranks: ['Peasant', 'Squire'],
    choices: [
      { label: 'Enter and joust! (5g)', costGold: 5, successChance: 0.4, success: { text: 'Against all odds you unhorsed a minor knight! The crowd is delirious. A peasant legend is born.', effects: { gold: 8, charm: 12, health: -8, path: { martial: 3 }, rankProgress: 12, reputation: 5 }, tone: 'good' }, failure: { text: 'You were unhorsed in 0.4 seconds, but the crowd loved your scream. Minor fame achieved.', effects: { gold: -5, charm: 6, health: -12 }, tone: 'bad' } },
      { label: 'Sell pies to the crowd', outcome: { text: 'You sold forty mince pies. Capitalism, even in 1340, finds a way.', effects: { gold: 9, charm: 2, path: { labour: 1 } }, tone: 'good' } },
      { label: 'Watch from a safe tree', outcome: { text: 'You watched from a tree and learned much about how NOT to fall off a horse.', effects: { wits: 3 }, tone: 'plain' } },
    ],
  },
  {
    id: 'peasant_confession',
    category: 'peasant',
    title: 'CONFESSION TIME',
    text: 'The priest asks if you have sinned this year. You have. Many times. Mostly about pies.',
    ageMin: 10,
    choices: [
      { label: 'Confess everything', outcome: { text: 'You confessed all. The priest needed a sit-down. Your soul is lighter; the village now knows about the pies.', effects: { faith: 12, charm: -3, path: { church: 2 } }, tone: 'good' } },
      { label: 'Lie boldly', outcome: { text: 'You claimed sainthood. The priest is suspicious but impressed by your confidence.', effects: { faith: -8, wits: 3, charm: 4, path: { court: 1 } }, tone: 'plain' } },
      { label: 'Donate to dodge it (4g)', costGold: 4, outcome: { text: 'A few coins in the box and the priest forgot his question entirely. Convenient.', effects: { gold: -4, faith: 6 }, tone: 'plain' } },
    ],
  },
  {
    id: 'peasant_wandering_knight',
    category: 'peasant',
    title: 'A WANDERING KNIGHT',
    text: 'A knight seeks a squire to carry his absurdly heavy armour. He squints at you.',
    ageMin: 12,
    ageMax: 18,
    ranks: ['Peasant'],
    once: true,
    choices: [
      { label: 'Beg to be his squire', successChance: 0.6, success: { text: 'He grunted approval — you are on the path to knighthood! (Or at least to heavy lifting.)', effects: { charm: 5, wits: 4, path: { martial: 4 }, rankProgress: 60, memory: { tag: 'took_squire_path', weight: 3 } }, tone: 'good' }, failure: { text: 'He looked you up and down, sighed, and chose the blacksmith’s daughter instead.', effects: { charm: -3 }, tone: 'bad' } },
      { label: 'Demand fair wages first', outcome: { text: 'He laughed, tossed you a coin, and rode off. Bold, but you remain a peasant.', effects: { charm: -3, gold: 5 }, tone: 'plain' } },
      { label: 'Hide behind the goose', outcome: { text: 'You hid behind Sir Quackbeard. The knight respected the goose, not you.', effects: { charm: -4, kinRel: { id: 'goose', delta: 3 } }, tone: 'plain' } },
    ],
  },
  {
    id: 'peasant_lucky_streak',
    category: 'peasant',
    title: 'AN UNCANNY STREAK',
    text: 'Dice, cards, coin-tosses — of late you simply cannot lose. The other gamblers mutter darkly about witchcraft.',
    ageMin: 14,
    requires: { hasTraits: ['lucky'] },
    weight: 1.5,
    choices: [
      { label: 'Ride the luck for all it is worth', successChance: 0.8, success: { text: 'You cleaned out the whole table and walked home whistling, pockets jingling.', effects: { gold: 16, charm: 4, path: { court: 1 } }, tone: 'good' }, failure: { text: 'Your luck finally blinked. You lost the lot — and a tooth, to a sore loser.', effects: { gold: -8, health: -5 }, tone: 'bad' } },
      { label: 'Quit while you are ahead', outcome: { text: 'You pocketed your winnings and left. The gamblers glared; fortune, like milk, can turn.', effects: { gold: 7, wits: 3 }, tone: 'good' } },
    ],
  },
  {
    id: 'peasant_sickly_winter',
    category: 'peasant',
    title: 'A CRUEL WINTER',
    text: 'The cold settles deep in your frail chest, as it always does. The herb-wife eyes you with pity and a price.',
    ageMin: 10,
    requires: { hasTraits: ['sickly'] },
    weight: 1.3,
    choices: [
      { label: 'Buy the strongest tonic (7g)', costGold: 7, outcome: { text: 'The tonic was vile and dear, but you saw the spring. For a sickly soul, that is a victory.', effects: { gold: -7, health: 14, faith: 2 }, tone: 'good' } },
      { label: 'Endure it by the hearth', successChance: 0.55, success: { text: 'You wrapped in every blanket you own and outlasted the cold. Barely.', effects: { health: -4, faith: 3 }, tone: 'plain' }, failure: { text: 'The fever took hold and very nearly took you. You emerge in spring, hollow-eyed.', effects: { health: -16 }, tone: 'bad' } },
    ],
  },
  {
    id: 'peasant_sweating_sickness',
    category: 'peasant',
    title: 'THE SWEATING SICKNESS',
    text: 'A fever sweeps the village. By morning you are clammy, shivering, and quietly terrified.',
    ageMin: 10,
    requires: { missingTags: ['ill', 'imprisoned'] },
    choices: [
      { label: 'Pay the herb-wife at once (6g)', costGold: 6, outcome: { text: 'Her tonic is bitter but swift. The fever breaks before it can take root.', effects: { gold: -6, health: -3 }, tone: 'good' } },
      { label: 'Sweat it out and pray', successChance: 0.5, success: { text: 'You sweated through three foul nights and woke clear-eyed. Spared, this time.', effects: { health: -6, faith: 4 }, tone: 'plain' }, failure: { text: 'The fever digs in for the long haul. This sickness will not pass quickly.', effects: { health: -8, addTags: ['ill'] }, tone: 'bad' } },
    ],
  },
  {
    id: 'outlaw_arrest',
    category: 'peasant',
    title: 'THE REEVE COMES KNOCKING',
    text: 'Word of your misdeeds has reached the reeve. Armed men are at your door, and they are not smiling.',
    ageMin: 14,
    weight: 1.4,
    requires: { missingTags: ['imprisoned'], maxReputation: -15 },
    choices: [
      { label: 'Bribe your way out (15g)', costGold: 15, outcome: { text: 'A heavy purse changes hands. The reeve discovers he was quite mistaken. Funny, that.', effects: { gold: -15, reputation: 2 }, tone: 'plain' } },
      { label: 'Make a run for it', successChance: 0.45, success: { text: 'Out the back and over three fences. Free, filthy, and faster than you look.', effects: { health: -4, path: { outlaw: 2 } }, tone: 'good' }, failure: { text: 'They caught you at the treeline and clapped you in irons.', effects: { prison: true, health: -6 }, tone: 'bad' } },
      { label: 'Surrender with dignity', outcome: { text: 'You go quietly. The dungeon door clangs shut behind you.', effects: { prison: true }, tone: 'bad' } },
    ],
  },
  {
    id: 'peasant_marriage_offer',
    category: 'peasant',
    title: 'A MATCH IS PROPOSED',
    text: 'The matchmaker has found you a suitor: kind-eyed, hard-working, owns nearly two goats.',
    ageMin: 16,
    ageMax: 40,
    once: true,
    requires: { missingTags: ['married'] },
    choices: [
      { label: 'Marry for love', outcome: { text: 'You wed! It is warm, it is real, and the goats are a fine dowry.', effects: { health: 4, charm: 4, addTags: ['married'], addKin: { kind: 'spouse' }, memory: { tag: 'married', weight: 3 } }, tone: 'good', next: 'arc_marriage_2', nextWhen: 'nextYear' } },
      { label: 'Hold out for nobility', requires: { statAtLeast: { charm: 50 } }, outcome: { text: 'You spurned the match, eyes fixed on a grander union. Ambitious. Possibly foolish.', effects: { charm: 2, path: { court: 2 } }, tone: 'plain' } },
      { label: 'Decline — you have a goose', outcome: { text: 'You explained that your heart belongs to a goose. The matchmaker left, deeply confused.', effects: { kinRel: { id: 'goose', delta: 8 } }, tone: 'plain' } },
    ],
  },
];
